services:
  - type: web
    name: p-frog-api
    env: node
    plan: free
    buildCommand: yarn install --frozen-lockfile && yarn build:server
    startCommand: node dist/apps/api/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRODUCTION
        value: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 27017
      - key: DB_SCHEMA
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
